'use client';
import { useLanguage, LanguageToggle } from '../components/language';

import { useMemo, useRef, useState, useEffect } from 'react';
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BarChart3, Check, CheckCheck, ChevronDown, ChevronRight, CircleHelp, CircleX, Database, DollarSign, FileCheck2, FileSpreadsheet, GitMerge, Layers3, LayoutDashboard, LoaderCircle, Menu, Plus, Search, ShieldCheck, Sparkles, Target, TrendingUp, Upload, X } from 'lucide-react';
import { STAGES } from '../lib/pipeline';
import ImportPanel from '../components/import-panel';

const formatCurrency = (n, code = 'USD', compact = false, language = 'en') => n === null ? (language === 'pt' ? 'Indisponível' : 'Unavailable') : new Intl.NumberFormat(language === 'pt' ? 'pt-BR' : 'en-US', { style: 'currency', currency: code, minimumFractionDigits: 0, maximumFractionDigits: compact ? 1 : 0, ...(compact ? { notation: 'compact' } : {}) }).format(n);
const number = n => new Intl.NumberFormat('en-US').format(n);
const multiple = n => n === null ? '—' : `${n.toFixed(2)}×`;
const decisionClass = s => ({ Scale: 'green', Maintain: 'blue', Optimize: 'amber', 'Review data': 'amber', 'Gather data': 'neutral' }[s]);
function download(name, text, type = 'text/csv;charset=utf-8') { const url = URL.createObjectURL(new Blob([text], { type })); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
function Logo({ small = false }) { return <div className={`logo ${small ? 'small' : ''}`}><BarChart3 size={small ? 18 : 22} strokeWidth={2.5} /></div>; }
function CampaignChart({ campaigns, code }) {
  const { t, language } = useLanguage();
  const currency = (n, code, compact) => formatCurrency(n, code, compact, language);
  const multiple = n => n === null ? '—' : new Intl.NumberFormat(language === 'pt' ? 'pt-BR' : 'en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n) + '×';
  const number = n => new Intl.NumberFormat(language === 'pt' ? 'pt-BR' : 'en-US').format(n);
  const max = Math.max(...campaigns.map(c => Math.max(c.spend, c.revenue)), 1);
  return <div className="bar-chart" role="img" aria-label="Grouped horizontal bars comparing ad spend and closed-won revenue per campaign. Exact values are available in the campaign table.">
    {campaigns.slice(0, 6).map(c => <div className="chart-row" key={c.id}><span className="chart-label" title={c.name}>{c.name}</span><div className="bar-track"><div className="chart-bar revenue" style={{ width: `${(c.revenue ?? 0) / max * 100}%`, visibility: c.revenue === null ? 'hidden' : 'visible' }} title={`Revenue: ${currency(c.revenue, code)}`} /><div className="chart-bar spend" style={{ width: `${c.spend / max * 100}%` }} title={`Spend: ${currency(c.spend, code)}`} /></div><span className="chart-multiple">{multiple(c.roas)}</span></div>)}
    {campaigns.some(c => c.revenue === null) && <p className="settings-hint">{t("Revenue bars are hidden where amounts are unavailable.")}</p>}<div className="chart-axis"><span>0</span>{[0.25, 0.5, 0.75, 1].map(v => <span key={v}>{currency(max * v, code, true)}</span>)}</div>
    {!campaigns.length && <div className="empty-state">{t("No valid ad campaigns to compare.")}</div>}
  </div>;
}

export default function Dashboard() {
  const { t, language } = useLanguage();
  const currency = (n, code, compact) => formatCurrency(n, code, compact, language);
  const multiple = n => n === null ? '—' : new Intl.NumberFormat(language === 'pt' ? 'pt-BR' : 'en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(n) + '×';
  const number = n => new Intl.NumberFormat(language === 'pt' ? 'pt-BR' : 'en-US').format(n);
  const [model, setModel] = useState(null); const [source, setSource] = useState(null); const [importKey, setImportKey] = useState(0);
  const view = 'Overview'; const [search, setSearch] = useState(''); const [decision, setDecision] = useState('All decisions'); const [sort, setSort] = useState('spend'); const [chart, setChart] = useState('Performance'); const [notice, setNotice] = useState(''); const [explanation, setExplanation] = useState(''); const [aiBusy, setAiBusy] = useState(false); const [aiError, setAiError] = useState('');
  const totals = model?.totals; const s = model?.stats; const code = model?.currency;
  const activeSource = useRef(source); activeSource.current = source;
  const activeLanguage = useRef(language); activeLanguage.current = language;
  useEffect(() => { setExplanation(''); setAiError(''); }, [language]);
  const visible = useMemo(() => (model?.campaigns || []).filter(c => c.name.toLowerCase().includes(search.toLowerCase()) && (decision === 'All decisions' || c.decision === decision)).sort((a, b) => (b[sort] ?? -1) - (a[sort] ?? -1)), [model, search, decision, sort]);
  const scale = (model?.campaigns || []).filter(c => c.decision === 'Scale').length;
  const optimize = (model?.campaigns || []).filter(c => c.decision === 'Optimize').length;
  useEffect(() => { if (notice) { const id = setTimeout(() => setNotice(''), 4000); return () => clearTimeout(id); } }, [notice]);
  const navigate = name => { const target = document.getElementById(name === 'Data quality' ? 'data-quality' : 'results'); if (target?.tagName === 'DETAILS') target.open = true; target?.scrollIntoView({ behavior: 'smooth' }); };
  const showMethodology = () => { const target = document.getElementById('methodology'); target.open = true; target.scrollIntoView({ behavior: 'smooth' }); };
  const showImport = () => document.getElementById('import').scrollIntoView({ behavior: 'smooth' });
  function clearData() { setModel(null); setSource(null); setImportKey(key => key + 1); setExplanation(''); setAiError(''); setNotice('Data cleared'); }
  async function explain() { setAiBusy(true); setAiError(''); try { const response = await fetch(`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/api/explain`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...source, language }), signal: AbortSignal.timeout(25000) }); const result = await response.json(); if (activeSource.current !== source || activeLanguage.current !== language) return; if (!response.ok) throw new Error(result.error || 'Explanation service is unavailable.'); setExplanation(result.text); } catch (e) { if (activeSource.current === source && activeLanguage.current === language) setAiError(e.name === 'TimeoutError' ? 'The explanation request timed out. Your metrics are unchanged.' : e.message); } finally { setAiBusy(false); } }
  const cards = model ? [
    { title: t("Total ad spend"), value: currency(totals.spend, code), icon: DollarSign, detail: `${number(s.acceptedAds)} validated ad rows`, caption: t("Across all accepted campaigns"), trend: t("All imported data"), kind: 'neutral' },
    { title: t("Customer acquisition cost"), value: currency(totals.cac, code), icon: Target, detail: `${number(totals.closed)} closed-won records`, caption: t("Ad spend ÷ closed-won records"), trend: 'CAC', kind: 'blue' },
    { title: t("Return on ad spend"), value: totals.roas === null ? t("Unavailable") : multiple(totals.roas), icon: TrendingUp, detail: totals.revenue === null ? t("Revenue column not detected or incomplete") : `${currency(totals.revenue, code)} attributed revenue`, caption: t("Closed-won revenue ÷ ad spend"), trend: 'ROAS', kind: 'green' },
    { title: t("Open pipeline revenue"), value: totals.open ? currency(totals.pipeline, code) : '—', icon: Layers3, detail: totals.open ? `${totals.open} matched open opportunities` : t("No matched open opportunities"), caption: t("Excludes won and lost records"), trend: t("Open pipeline"), kind: 'blue' },
  ] : [];
  return <div className="app-shell one-page">
<div className="main-shell"><header className="demo-topbar"><a className="brand" href="#top"><Logo /><span>Pipeline Pulse</span></a><nav aria-label={t("Page sections")}><a href="#import">{t("Import")}</a>{model && <><a href="#results">{t("Results")}</a><a href="#summary">{t("Summary")}</a></>}</nav><LanguageToggle /><span className="prototype-label">{t("PROTOTYPE")}</span></header>
      <main id="top"><div className="page-heading"><div><div className="heading-kicker">{t("YOUR MARKETING, CONNECTED")}</div><h1>{view === 'Overview' ? t("Performance overview") : view}</h1><p>{view === 'Overview' ? t("From ad spend to closed deals. See what’s really working.") : view === 'Campaigns' ? 'Compare investment, revenue, and the next step for every campaign.' : view === 'Data sources' ? 'Your advertising and CRM exports, brought together.' : 'Every row accounted for. Every number traceable.'}</p></div></div>
      {model && <div className="context-strip"><div><span className="status-pill green"><span className="status-dot" />{t("Your data")}</span><span className="context-text">{source.names.ads} + {source.names.crm}</span></div><span className="date-label">{model.dateRange ? model.dateRange.join(' — ') : t("All imported records")}<span className="currency-label">{code}</span></span></div>}
      <>
        <ImportPanel key={importKey} onReset={clearData} onAnalyze={(data, files) => { setModel(data); setSource(files); setExplanation(''); setAiError(''); setSearch(''); setDecision('All decisions'); setNotice(`${data.stats.raw} rows analyzed · ${data.stats.duplicates} duplicates removed`); }} />
        {model ? <>
        <section id="results" className="metric-grid" aria-label={t("Marketing key performance indicators")}>{cards.map((c, i) => <article className={`metric-card metric-${i}`} key={t(c.title)}><div className="metric-top"><span>{c.title}</span><c.icon size={18} /></div><strong className="metric-value">{t(c.value)}</strong><div className="metric-detail"><span className={`metric-tag ${c.kind}`}>{t(c.trend)}</span><span>{t(c.detail)}</span></div><div className="metric-caption">{t(c.caption)}</div></article>)}</section>
        {view === 'Overview' && <><section className="reconciliation-strip"><div className="reconciliation-title"><div className="icon-tile"><GitMerge size={21} /></div><div><strong>{t("Your data, reconciled")}</strong><span>{t("From messy exports to a clear picture")}</span></div></div><div className="recon-stat"><strong>{number(s.raw)}</strong><span>{t("Rows analyzed")}</span></div><div className="recon-stat"><strong>{number(s.duplicates)}</strong><span>{t("Duplicates removed")}</span></div><div className="recon-stat"><strong>{number(s.matched)}<CheckCheck size={15} /></strong><span>{t("CRM records matched")}</span></div><button className="quality-link" onClick={() => navigate('Data quality')}><span className={`quality-mini ${s.unmatched + s.quarantined ? 'amber' : 'green'}`}><ShieldCheck size={14} />{s.unmatched + s.quarantined ? t("Needs review") : t("Checks passed")}</span><ChevronRight size={17} /></button></section>
        <div className="chart-grid"><section className="panel performance-panel"><div className="panel-heading"><div><h2>{t("Investment & return")}</h2><p>{t("Ad spend and closed-won revenue by campaign")}</p></div><div className="segmented-control">{['Performance', 'Efficiency'].map(v => <button className={chart === v ? 'selected' : ''} onClick={() => setChart(v)} key={v}>{t(v)}</button>)}</div></div><div className="chart-legend"><span><i className="legend-dot revenue" />{t("Closed-won revenue")}</span><span><i className="legend-dot spend" />{t("Ad spend")}</span><span className="legend-roas">ROAS</span></div>{chart === 'Performance' ? <CampaignChart campaigns={model.campaigns} code={code} /> : <div className="efficiency-chart">{model.campaigns.map(c => <div key={c.id}><span>{c.name}</span><div className="efficiency-track"><div style={{ width: `${Math.min(100, (c.roas || 0) / Math.max(...model.campaigns.map(x => x.roas || 0), 3) * 100)}%` }} className={c.roas >= 3 ? 'good' : 'weak'} /></div><strong>{multiple(c.roas)}</strong></div>)}<p>{t("Scale threshold: 3× ROAS and at least 3 closed-won records. Data issues pause recommendations.")}</p></div>}<div className="chart-footer"><Activity size={14} /><span>{s.campaigns} {t("campaigns")} · {t("Attributed revenue only")}</span></div></section>
        <section className="panel outcomes-panel"><div className="panel-heading"><div><h2>{t("Revenue at a glance")}</h2><p>{t("Where matched opportunities stand")}</p></div><TrendingUp size={19} className="muted" /></div><div className="revenue-total"><span>{t("Closed-won revenue")}</span><strong>{currency(totals.revenue, code)}</strong><span className="green-text"><CheckCheck size={14} />{totals.closed} {t("closed-won records")}</span></div><div hidden={totals.revenue === null || totals.pipeline === null} className="revenue-stack" aria-label={`Won ${currency(totals.revenue, code)}; open ${currency(totals.pipeline, code)}`}><span style={{ flex: totals.revenue || 0.001 }} /><span style={{ flex: totals.pipeline || 0.001 }} /></div><div className="revenue-breakdown"><div><span><i className="legend-dot revenue" />{t("Closed won")}</span><strong>{currency(totals.revenue, code)}</strong></div><div><span><i className="legend-dot pipeline" />{t("Open pipeline")}</span><strong>{totals.open ? currency(totals.pipeline, code) : t("No matched open opportunities")}</strong></div></div><div className="outcome-note"><div className="outcome-note-icon"><Target size={18} /></div><div><strong>{s.matchRate === null ? t("No matchable records") : t(`${s.matchRate.toFixed(0)}% campaign match rate`)}</strong><p>{s.unmatched ? t(`${s.unmatched} records need reconciliation.`) : t("Every accepted CRM record is connected.")}</p></div></div></section></div></>}
        <section className="panel campaign-panel"><div className="panel-heading"><div><h2>{t("Campaign performance")}{' '}<span className="count-badge">{s.campaigns}</span></h2><p>{t("A clear view of where to invest next.")}</p></div><div className="table-controls"><div className="search-field"><Search size={15} /><input aria-label={t("Search campaigns")} placeholder={t("Search campaigns…")} value={search} onChange={e => setSearch(e.target.value)} /></div><select aria-label={t("Filter decision")} value={decision} onChange={e => setDecision(e.target.value)}>{['All decisions', 'Scale', 'Maintain', 'Optimize', 'Review data', 'Gather data'].map(d => <option key={d} value={d}>{t(d)}</option>)}</select></div></div><div className="table-scroll"><table><thead><tr><th>{t("Campaign")}</th><th><button onClick={() => setSort('spend')}>{t("Ad spend")}{' '}{sort === 'spend' ? '↓' : ''}</button></th><th><button onClick={() => setSort('revenue')}>{t("Revenue")}{' '}{sort === 'revenue' ? '↓' : ''}</button></th><th>{t("Closed won")}</th><th>CAC</th><th><button onClick={() => setSort('roas')}>ROAS {sort === 'roas' ? '↓' : ''}</button></th><th>{t("Decision")}{' '}<button className="inline-help" aria-label={t("Decision methodology")} onClick={() => showMethodology()}><CircleHelp size={13} /></button></th></tr></thead><tbody>{visible.map((c, index) => <tr key={c.id}><td><div className="campaign-cell"><span className={`campaign-icon color-${index % 3}`}><Target size={16} /></span><div><strong>{c.name}</strong><span>{c.adRows} {t("ad rows")} · {c.leads} {t("CRM records")}</span></div></div></td><td>{currency(c.spend, code)}</td><td>{currency(c.revenue, code)}</td><td>{c.closed}</td><td>{c.cac === null ? '—' : currency(c.cac, code)}</td><td><strong className={c.roas >= 3 ? 'green-text' : ''}>{multiple(c.roas)}</strong></td><td><span className={`decision-badge ${decisionClass(c.decision)}`}>{c.decision === 'Scale' ? <ArrowUpRight size={13} /> : c.decision === 'Maintain' ? <Check size={13} /> : <Activity size={13} />}{t(c.decision)}</span></td></tr>)}</tbody></table>{!visible.length && <div className="empty-state">{t("No campaigns match your filters.")}</div>}</div><div className="table-footer"><span>{t("Showing")} {visible.length} {t("of")} {s.campaigns} {t("campaigns")}</span><span><ShieldCheck size={14} />{t("Decisions follow fixed rules, not AI predictions")}</span></div></section>

      <details id="data-sources" className="panel onepage-details"><summary>{t("Source files & detected columns")}{' '}<ChevronDown size={16} /></summary><div className="detail-content"><div className="source-grid">{['ads', 'crm'].map(kind => <section className="panel source-card" key={kind}><div className="source-icon"><FileSpreadsheet size={28} /></div><span className="status-pill green">{t("Loaded")}</span><h2>{kind === 'ads' ? t("Advertising export") : t("CRM export")}</h2><p>{source.names[kind]}</p><div className="source-details"><div><span>{t("Imported rows")}</span><strong>{kind === 'ads' ? s.adRows : s.crmRows}</strong></div><div><span>{t("Accepted rows")}</span><strong>{kind === 'ads' ? s.acceptedAds : s.acceptedCrm}</strong></div><div><span>{t("Detected columns")}</span><strong>{model.schema[kind].length}</strong></div></div><div className="column-tags">{model.schema[kind].map(h => <span key={h}>{h}</span>)}</div></section>)}</div><section className="panel source-actions"><div><h2>{t("Ready for your own data?")}</h2><p>{t("Import both sources together to keep your analysis consistent.")}</p></div><button className="button primary" onClick={() => showImport()}><Upload size={17} />{t("Import a new dataset")}</button><button className="button secondary" onClick={clearData}>{t("Clear data")}</button></section></div></details>
      <details id="data-quality" className="panel onepage-details"><summary>{t("Data quality & reconciliation")}{' '}<ChevronDown size={16} /></summary><div className="detail-content"><div className="quality-grid">{[['Imported rows', s.raw], ['Duplicates removed', s.duplicates], ['Quarantined rows', s.quarantined], ['Unmatched records', s.unmatched]].map(([name, value]) => <div className="panel quality-card" key={name}><span>{t(name)}</span><strong>{number(value)}</strong></div>)}</div><section className="panel quality-report"><div className="panel-heading"><div><h2>{t("Reconciliation report")}</h2><p>{s.raw} {t("input rows")} = {s.acceptedAds + s.acceptedCrm} {t("accepted")} + {s.duplicates} {t("duplicates")} + {s.quarantined} {t("quarantined")}. {t("Unmatched records")}: {s.unmatched}.</p></div><ShieldCheck size={23} /></div>{!model.warnings.length && <div className="success-note"><CheckCheck size={20} />{t("All data checks passed.")}</div>}{model.warnings.map(w => <div className="warning-note" key={w}><CircleHelp size={18} /><span>{t(w)}</span></div>)}<div className="table-scroll"><table><thead><tr><th>{t("Source")}</th><th>{t("CSV record")}</th><th>{t("Issue")}</th></tr></thead><tbody>{model.issues.slice(0, 100).map((issue, i) => <tr key={`i${i}`}><td>{issue.source.toUpperCase()}</td><td>{issue.line}</td><td>{t(issue.reason)}</td></tr>)}{model.unmatched.slice(0, 100).map((row, i) => <tr key={`u${i}`}><td>CRM</td><td>{row.line}</td><td>{t(row.reason)}: {row.campaign || row.campaignId}</td></tr>)}</tbody></table>{!s.quarantined && !s.unmatched && <div className="empty-state"><ShieldCheck size={28} /><strong>{t("No issues to resolve")}</strong><p>{t("Your accepted data is ready for analysis.")}</p></div>}</div><div className="table-footer"><span>{t("Up to 100 issues per category shown")}</span><button className="text-button" onClick={() => download('markops-quality-report.json', JSON.stringify({ stats: s, warnings: model.warnings, issues: model.issues, unmatched: model.unmatched.map(r => ({ line: r.line, reason: r.reason, campaign: r.campaign })) }, null, 2), 'application/json')}>{t("Download full report")}{' '}<ArrowDownToLine size={14} /></button></div></section><section className="panel pipeline-panel"><h2>{t("From raw data to a clear decision")}</h2><div className="pipeline-stages">{STAGES.map((stage, i) => <div key={stage}><span>{String(i + 1).padStart(2, '0')}</span><strong>{t(stage)}</strong>{i < 9 && <ArrowRight size={15} />}</div>)}</div></section></div></details>
    <details id="methodology" className="panel onepage-details"><summary>{t("How the numbers become decisions")}{' '}<ChevronDown size={16} /></summary><div className="methodology"><p><strong>CAC</strong>{t("is accepted ad spend divided by matched closed-won CRM records. Record IDs are optional; without them, identical normalized rows count once. this is a record-based acquisition metric, not unique people across separate deals.")}</p><p><strong>ROAS</strong>{t("is matched closed-won revenue divided by accepted ad spend.")}{' '}<strong>{t("Open pipeline")}</strong>{t("includes matched open opportunities only. Zero denominators are unavailable.")}</p><p><strong>{t("Reconciliation")}</strong>{t("uses exact campaign IDs, then a unique normalized campaign name when a CRM campaign ID is absent. A unique equivalent set of campaign words also matches across word order, camel case, percent notation and abandon/abandoner variants. Years, regions and audience sizes are preserved. Ambiguous names stay unmatched; conflicting IDs never fall back to a name match.")}</p><p><strong>{t("Decisions")}</strong>{t("require at least 3 closed-won records and positive spend. ROAS ≥ 3: Scale; ≥ 1: Maintain; below 1: Optimize. Insufficient evidence: Gather data. Any unmatched or quarantined row: Review data for all campaigns.")}</p><p><strong>{t("Scope")}</strong>{t("is all accepted imported records. Use exports from the same period and attribution model. This prototype does not infer multi-touch attribution or convert currencies.")}</p><p><strong>{t("AI")}</strong>{t("is optional and only explains calculated aggregates. A server-side explanation service must be configured. Until then, the summary is explicitly rule-based.")}</p></div></details>
        <section className="ai-panel" id="summary"><div className="ai-heading"><div className="ai-icon"><Sparkles size={21} /></div><div><h2>{t("Intelligence summary")}{' '}<span>{explanation ? t("AI EXPLANATION") : t("RULE-BASED PREVIEW")}</span></h2><p>{t("Your numbers tell a story. Here’s the picture.")}</p></div><button className="button secondary" disabled={aiBusy} onClick={explain}>{aiBusy ? <LoaderCircle size={15} className="spin" /> : <Sparkles size={15} />}{aiBusy ? t("Explaining…") : explanation ? t("Refresh explanation") : t("Generate AI summary")}</button></div>{explanation ? <p className="ai-copy">{explanation}</p> : <div className="insight-grid"><div><span className="insight-number">01</span><h3>{t(scale ? `${scale} campaigns meet the scale rule` : t("Validate before you scale"))}</h3><p>{scale ? t("These campaigns returned at least 3× spend with 3 or more closed-won records.") : t("No campaign currently meets the minimum evidence and data-quality requirements.")}</p></div><div><span className="insight-number">02</span><h3>{t(optimize ? `${optimize} campaigns need attention` : t("Keep the full funnel in view"))}</h3><p>{t(optimize ? t("Attributed revenue is below spend. Review audience, creative, and conversion quality.") : !totals.open ? t("No matched open opportunities. Pipeline value cannot be determined from matched records.") : totals.pipeline === null ? t("Some open opportunity amounts are missing. Review the CRM amount column.") : `${currency(totals.pipeline, code)} in matched open pipeline is not yet realized revenue.`)}</p></div><div><span className="insight-number">03</span><h3>{s.unmatched + s.quarantined ? t("Resolve data gaps first") : t("A clean foundation for decisions")}</h3><p>{t(s.unmatched + s.quarantined ? `${s.unmatched} unmatched records and ${s.quarantined} quarantined rows require review.` : `${s.duplicates} duplicate rows removed. ${s.matched} CRM records matched to your campaigns.`)}</p></div></div>}{aiError && <div className="ai-error" role="status">{t(aiError)}</div>}<div className="ai-footnote"><ShieldCheck size={13} />{t("AI explains precomputed results only. Generating a summary sends aggregate metrics to the configured explanation service; raw records and campaign names stay here.")}</div></section>
        </> : <section className="panel empty-state" aria-label={t("No data uploaded")}><FileSpreadsheet size={32} /><h2>{t("Upload your files to get started")}</h2><p>{t("Your metrics, campaign results, and summary will appear after analysis.")}</p></section>}
      </>
      <footer className="page-footer"><span><Logo small />Pipeline Pulse</span><span>{t("Calculated from your data.")}</span></footer>
      </main>
    </div>


    {notice && <div className="toast" role="status"><CheckCheck size={18} />{t(notice)}<button aria-label={t("Dismiss notification")} onClick={() => setNotice('')}><X size={15} /></button></div>}
  </div>;
}
