export const portuguese = {
'Import':'Importar','Results':'Resultados','Summary':'Resumo','PROTOTYPE':'PROTÓTIPO','YOUR MARKETING, CONNECTED':'SEU MARKETING, CONECTADO','Performance overview':'Visão geral de desempenho','From ad spend to closed deals. See what’s really working.':'Do investimento em anúncios aos negócios fechados. Veja o que funciona.',
'Bring your data together':'Reúna seus dados','Drop in your exports. We detect the format and connect spend to revenue.':'Envie suas exportações. Detectamos o formato e conectamos investimento e receita.','Processed in your browser':'Processado no seu navegador','Advertising CSV':'CSV de anúncios','CRM CSV':'CSV do CRM','Choose file':'Escolher arquivo','Replace':'Substituir','Detection settings':'Configurações de detecção','Clear data':'Limpar dados','Analyze data':'Analisar dados','Reconciling…':'Conciliando…','Upload your files to get started':'Envie seus arquivos para começar','Your metrics, campaign results, and summary will appear after analysis.':'Suas métricas, resultados por campanha e resumo aparecerão após a análise.','Calculated from your data.':'Calculado a partir dos seus dados.','Your data':'Seus dados','All imported records':'Todos os registros importados',
'Total ad spend':'Investimento total em anúncios','Customer acquisition cost':'Custo de aquisição de clientes','Return on ad spend':'Retorno sobre investimento em anúncios','Open pipeline revenue':'Valor das oportunidades em aberto','Across all accepted campaigns':'Todas as campanhas aceitas','All imported data':'Todos os dados importados','Ad spend ÷ closed-won records':'Investimento ÷ registros ganhos','Closed-won revenue ÷ ad spend':'Receita ganha ÷ investimento','Excludes won and lost records':'Exclui negócios ganhos e perdidos','Open pipeline':'Oportunidades em aberto','No matched open opportunities':'Nenhuma oportunidade em aberto vinculada','Unavailable':'Indisponível','Revenue column not detected or incomplete':'Coluna de receita não detectada ou incompleta',
'Your data, reconciled':'Seus dados, conciliados','From messy exports to a clear picture':'De exportações desorganizadas a uma visão clara','Rows analyzed':'Linhas analisadas','Duplicates removed':'Duplicatas removidas','CRM records matched':'Registros do CRM vinculados','Needs review':'Requer revisão','Checks passed':'Verificações aprovadas','Investment & return':'Investimento e retorno','Ad spend and closed-won revenue by campaign':'Investimento e receita de negócios ganhos por campanha','Performance':'Desempenho','Efficiency':'Eficiência','Closed-won revenue':'Receita de negócios ganhos','Ad spend':'Investimento em anúncios','Revenue':'Receita','Revenue at a glance':'Visão geral da receita','Where matched opportunities stand':'Situação das oportunidades vinculadas','Closed won':'Negócios ganhos','Closed lost':'Negócios perdidos','No matchable records':'Nenhum registro vinculável','Every accepted CRM record is connected.':'Todos os registros aceitos do CRM estão vinculados.',
'Campaign performance':'Desempenho por campanha','A clear view of where to invest next.':'Uma visão clara de onde investir a seguir.','Campaign':'Campanha','Decision':'Decisão','Search campaigns…':'Buscar campanhas…','Search campaigns':'Buscar campanhas','Filter decision':'Filtrar decisão','All decisions':'Todas as decisões','Scale':'Aumentar investimento','Maintain':'Manter','Optimize':'Otimizar','Review data':'Revisar dados','Gather data':'Coletar dados','No campaigns match your filters.':'Nenhuma campanha corresponde aos filtros.','Decisions follow fixed rules, not AI predictions':'Decisões seguem regras fixas, não previsões de IA','Decision methodology':'Metodologia das decisões',
'Source files & detected columns':'Arquivos de origem e colunas detectadas','Loaded':'Carregado','Advertising export':'Exportação de anúncios','CRM export':'Exportação do CRM','Imported rows':'Linhas importadas','Accepted rows':'Linhas aceitas','Detected columns':'Colunas detectadas','Ready for your own data?':'Pronto para importar outros dados?','Import both sources together to keep your analysis consistent.':'Importe as duas fontes juntas para manter a análise consistente.','Import a new dataset':'Importar novos dados','Data quality & reconciliation':'Qualidade dos dados e conciliação','Quarantined rows':'Linhas isoladas','Unmatched records':'Registros não vinculados','Reconciliation report':'Relatório de conciliação','All data checks passed.':'Todas as verificações foram aprovadas.','Source':'Origem','CSV record':'Registro CSV','Issue':'Problema','No issues to resolve':'Nenhum problema a resolver','Your accepted data is ready for analysis.':'Seus dados aceitos estão prontos para análise.','Up to 100 issues per category shown':'Exibindo até 100 problemas por categoria','Download full report':'Baixar relatório completo','From raw data to a clear decision':'Dos dados brutos a uma decisão clara','How the numbers become decisions':'Como os números se tornam decisões','Reconciliation':'Conciliação','Decisions':'Decisões','Scope':'Escopo','AI':'IA',
'Schema validation':'Validação do esquema','Normalization':'Normalização','Deduplication':'Remoção de duplicatas','Campaign reconciliation':'Conciliação de campanhas','Canonical dataset':'Conjunto de dados padronizado','Data-quality evaluation':'Avaliação da qualidade dos dados','Deterministic KPIs':'Indicadores determinísticos','Decision classification':'Classificação das decisões','Dashboard model':'Modelo do painel','Explanation only':'Somente explicação',
'Intelligence summary':'Resumo da análise','AI EXPLANATION':'EXPLICAÇÃO POR IA','RULE-BASED PREVIEW':'PRÉVIA BASEADA EM REGRAS','Your numbers tell a story. Here’s the picture.':'Entenda o que seus números mostram.','Explaining…':'Gerando explicação…','Refresh explanation':'Atualizar explicação','Generate AI summary':'Gerar resumo com IA','Validate before you scale':'Valide antes de aumentar o investimento','Keep the full funnel in view':'Acompanhe todo o funil','Resolve data gaps first':'Resolva as lacunas nos dados primeiro','A clean foundation for decisions':'Uma base confiável para decisões','No campaign currently meets the minimum evidence and data-quality requirements.':'Nenhuma campanha atende aos requisitos mínimos de evidências e qualidade dos dados.','These campaigns returned at least 3× spend with 3 or more closed-won records.':'Estas campanhas geraram pelo menos 3× o investimento, com 3 ou mais registros ganhos.','Attributed revenue is below spend. Review audience, creative, and conversion quality.':'A receita atribuída está abaixo do investimento. Revise público, criativos e qualidade das conversões.','No matched open opportunities. Pipeline value cannot be determined from matched records.':'Nenhuma oportunidade em aberto vinculada. Não é possível determinar seu valor a partir dos registros vinculados.','Some open opportunity amounts are missing. Review the CRM amount column.':'Faltam valores em algumas oportunidades em aberto. Revise a coluna de valor do CRM.',
'AI explains precomputed results only. Generating a summary sends aggregate metrics to the configured explanation service; raw records and campaign names stay here.':'A IA apenas explica resultados já calculados. A geração do resumo envia métricas agregadas ao serviço configurado; registros brutos e nomes de campanhas permanecem aqui.',
'Common formats are automatic. Confirm ambiguous dates or custom fields here. Unknown fields are never silently guessed.':'Formatos comuns são detectados automaticamente. Confirme datas ambíguas ou campos personalizados aqui. Campos desconhecidos não são adivinhados.','Reporting currency':'Moeda do relatório','Auto-detect · USD if unspecified':'Detectar automaticamente · USD se não informado','Number format':'Formato numérico','Auto-detect per value':'Detectar por valor','1,234.56 · decimal point':'1,234.56 · ponto decimal','1.234,56 · decimal comma':'1.234,56 · vírgula decimal','Advertising fields':'Campos dos anúncios','CRM fields':'Campos do CRM','Auto-detect':'Detectar automaticamente','Date order':'Ordem das datas','Auto-detect from this file':'Detectar a partir deste arquivo','Day / month / year':'Dia / mês / ano','Month / day / year':'Mês / dia / ano','Some dates need a date-order choice or correction.':'Algumas datas precisam de uma ordem definida ou correção.','Custom CRM stages':'Etapas personalizadas do CRM','Choose their meaning. Unmapped stages are quarantined.':'Escolha o significado de cada etapa. Etapas não mapeadas são isoladas.','Column in your file':'Coluna no seu arquivo','Sample values':'Exemplos de valores','Optional · deduplicating by row contents':'Opcional · remoção de duplicatas pelo conteúdo','Not detected · choose the amount column below':'Não detectado · escolha a coluna de valor abaixo','Choose a column below':'Escolha uma coluna abaixo','Data cleared':'Dados removidos','Revenue bars are hidden where amounts are unavailable.':'Barras de receita ficam ocultas quando os valores estão indisponíveis.','No valid ad campaigns to compare.':'Nenhuma campanha válida para comparar.',
};
export function translate(text, language) {
  if (language !== 'pt' || typeof text !== 'string') return text;
  if (portuguese[text]) return portuguese[text];
  for (const [pattern, replacement] of messages) if (pattern.test(text)) return text.replace(pattern, replacement);
  return text.replace(/validated ad rows/g,'linhas de anúncios validadas').replace(/closed-won records/g,'registros ganhos').replace(/matched open opportunities/g,'oportunidades em aberto vinculadas').replace(/attributed revenue/g,'receita atribuída').replace(/campaign match rate/g,'de vinculação de campanhas').replace(/records need reconciliation\./g,'registros precisam de conciliação.').replace(/campaigns meet the scale rule/g,'campanhas atendem à regra de expansão').replace(/campaigns need attention/g,'campanhas precisam de atenção').replace(/in matched open pipeline is not yet realized revenue\./g,'em oportunidades vinculadas ainda não é receita realizada.').replace(/unmatched records and/g,'registros não vinculados e').replace(/quarantined rows require review\./g,'linhas isoladas precisam de revisão.').replace(/duplicate rows removed\./g,'duplicatas removidas.').replace(/CRM records matched to your campaigns\./g,'registros do CRM vinculados às suas campanhas.').replace(/rows analyzed/g,'linhas analisadas').replace(/duplicates removed/g,'duplicatas removidas');
}
Object.assign(portuguese, {
'is accepted ad spend divided by matched closed-won CRM records. Record IDs are optional; without them, identical normalized rows count once. this is a record-based acquisition metric, not unique people across separate deals.':'é o investimento aceito dividido pelos registros ganhos vinculados. IDs são opcionais; sem eles, linhas normalizadas idênticas contam uma vez. A métrica conta registros, não pessoas únicas entre negócios distintos.',
'is matched closed-won revenue divided by accepted ad spend.':'é a receita ganha vinculada dividida pelo investimento aceito.',
'includes matched open opportunities only. Zero denominators are unavailable.':'inclui apenas oportunidades em aberto vinculadas. Divisões por zero ficam indisponíveis.',
'uses exact campaign IDs, then a unique normalized campaign name when a CRM campaign ID is absent. A unique equivalent set of campaign words also matches across word order, camel case, percent notation and abandon/abandoner variants. Years, regions and audience sizes are preserved. Ambiguous names stay unmatched; conflicting IDs never fall back to a name match.':'usa IDs exatos ou um nome normalizado único quando o ID está ausente. Também reconhece conjuntos equivalentes de palavras, mudanças de ordem, camel case, porcentagens e variantes abandon/abandoner. Anos, regiões e tamanhos de público são preservados. Nomes ambíguos não são vinculados; IDs conflitantes não são substituídos por nomes.',
'require at least 3 closed-won records and positive spend. ROAS ≥ 3: Scale; ≥ 1: Maintain; below 1: Optimize. Insufficient evidence: Gather data. Any unmatched or quarantined row: Review data for all campaigns.':'exigem pelo menos 3 registros ganhos e investimento positivo. ROAS ≥ 3: aumentar investimento; ≥ 1: manter; abaixo de 1: otimizar. Evidências insuficientes: coletar dados. Qualquer linha não vinculada ou isolada exige revisão de todas as campanhas.',
'is all accepted imported records. Use exports from the same period and attribution model. This prototype does not infer multi-touch attribution or convert currencies.':'abrange todos os registros importados aceitos. Use exportações do mesmo período e modelo de atribuição. O protótipo não infere atribuição multitoque nem converte moedas.',
'is optional and only explains calculated aggregates. A server-side explanation service must be configured. Until then, the summary is explicitly rule-based.':'é opcional e apenas explica valores agregados já calculados. Um serviço de explicação deve ser configurado no servidor. Até lá, o resumo é baseado em regras.',
'Scale threshold: 3× ROAS and at least 3 closed-won records. Data issues pause recommendations.':'Limite de expansão: ROAS de 3× e pelo menos 3 registros ganhos. Problemas nos dados suspendem recomendações.',
'Detects headers, column types, and unique campaign values shared by both files. Supports decimal commas/points, currency affixes, spaces, and apostrophe grouping. One separator followed by three digits means thousands (1.234 → 1,234). Ambiguous dates such as 03/04/2026 need evidence or your choice.':'Detecta cabeçalhos, tipos de coluna e campanhas únicas compartilhadas pelos arquivos. Aceita vírgula ou ponto decimal, símbolos monetários, espaços e apóstrofos. Um separador seguido por três dígitos indica milhar (1.234 → 1234). Datas ambíguas como 03/04/2026 exigem evidências ou sua escolha.',
'Select:':'Selecione:','Ambiguous:':'Ambíguo:','Detected:':'Detectado:','Inspect advertising columns and sample values':'Inspecionar colunas de anúncios e exemplos','Inspect CRM columns and sample values':'Inspecionar colunas do CRM e exemplos','spend':'investimento','campaign':'campanha','campaign Id':'ID da campanha','id':'ID','revenue':'receita','date':'data','currency':'moeda','status':'etapa','Comma':'Vírgula','Semicolon':'Ponto e vírgula','Tab':'Tabulação','Pipe':'Barra vertical','rows':'linhas','ad rows':'linhas de anúncios','CRM records':'registros do CRM','campaigns':'campanhas','Attributed revenue only':'Somente receita atribuída','Showing':'Exibindo','of':'de',
'Choose a CSV, TSV, or delimited text export.':'Escolha uma exportação CSV, TSV ou de texto delimitado.','File exceeds the 5 MB limit.':'O arquivo excede o limite de 5 MB.','Amount is missing, negative, ambiguous, or invalid for the selected number format.':'Valor ausente, negativo, ambíguo ou inválido para o formato numérico escolhido.','Unknown or ambiguous CRM stage; use a supported stage.':'Etapa do CRM desconhecida ou ambígua; use uma etapa reconhecida.','Missing or invalid campaign reference.':'Referência da campanha ausente ou inválida.','No matching ad campaign':'Nenhuma campanha de anúncios correspondente','Ambiguous campaign name':'Nome de campanha ambíguo','No matched open opportunities. Pipeline value is unavailable, not zero.':'Nenhuma oportunidade em aberto vinculada. O valor está indisponível, não é zero.','Some matched CRM amounts are blank. Affected revenue, ROAS, or pipeline totals are unavailable rather than treating missing values as zero.':'Alguns valores vinculados do CRM estão em branco. Receita, ROAS ou oportunidades afetadas ficam indisponíveis; valores ausentes não são tratados como zero.',
'Page sections':'Seções da página','Marketing key performance indicators':'Indicadores de desempenho de marketing','No data uploaded':'Nenhum dado enviado','Dismiss notification':'Fechar notificação',
});
Object.assign(portuguese, {
'Column count does not match the header.':'Quantidade de colunas diferente do cabeçalho.','Repeated header row excluded.':'Cabeçalho repetido excluído.','Spreadsheet formula or executable cell rejected.':'Fórmula de planilha ou célula executável rejeitada.','Invalid or ambiguous date. Choose day/month or month/day in detection settings.':'Data inválida ou ambígua. Escolha dia/mês ou mês/dia nas configurações.','This file is empty. Choose a CSV with a header and data rows.':'Arquivo vazio. Escolha um CSV com cabeçalho e linhas de dados.','Headers must be nonempty and unique, including after normalization.':'Cabeçalhos devem ser preenchidos e únicos, inclusive após normalização.','The CSV contains headers but no data rows.':'O CSV contém cabeçalhos, mas não tem linhas de dados.','Export preamble lines were skipped before the detected headers.':'Linhas introdutórias foram ignoradas antes dos cabeçalhos detectados.','One or both sources have no accepted records. Attributed KPIs are incomplete.':'Uma ou ambas as fontes não têm registros aceitos. Os indicadores atribuídos estão incompletos.','AI explanations are not configured yet. The rule-based summary above remains available. Configure LLM_EXPLANATION_URL on the server to enable AI.':'As explicações por IA ainda não estão configuradas. O resumo baseado em regras continua disponível. Configure LLM_EXPLANATION_URL no servidor para ativar a IA.','The explanation service could not complete this request. Your calculated results are unchanged. Try again later.':'O serviço de explicação não concluiu a solicitação. Os resultados calculados não mudaram. Tente novamente mais tarde.','No revenue column detected. Revenue, ROAS, and pipeline value are unavailable. Match counts, closed-won counts, and CAC remain available. Map an amount column in detection settings if one exists.':'Nenhuma coluna de receita detectada. Receita, ROAS e valor das oportunidades estão indisponíveis. Contagens e CAC continuam disponíveis. Se existir, selecione uma coluna de valor nas configurações.',
});
const messages = [
[/^(\d+) accepted CRM rows have no record ID\..*$/, '$1 linhas aceitas do CRM não têm ID. Linhas normalizadas idênticas são removidas; linhas diferentes não podem ser associadas à mesma pessoa ou negócio. O CAC conta registros ganhos distintos.'],
[/^(\d+) CRM records matched by equivalent campaign words\..*$/, '$1 registros do CRM vinculados por palavras equivalentes. Ordem, camel case, porcentagens e variantes abandon/abandoner foram normalizados; anos, regiões e tamanhos de público foram preservados.'],
[/^(\d+) ad rows have no date\..*$/, '$1 linhas de anúncios não têm data. Esta é uma visão de todos os dados, não uma comparação por período.'],
[/^(\d+) CRM records are unmatched and excluded.*$/, '$1 registros do CRM não foram vinculados e estão excluídos da receita, oportunidades, CAC e ROAS atribuídos.'],
[/^(\d+) rows were quarantined\..*$/, '$1 linhas foram isoladas. Resolva os problemas antes de agir sobre as recomendações.'],
[/^Rows without a currency column are assumed to be (.+)\.$/, 'Linhas sem coluna de moeda são consideradas em $1.'],
[/^Missing (ads|crm) columns: (.+)\. Select the matching columns in detection settings\.$/, 'Colunas ausentes ($1): $2. Selecione as colunas correspondentes nas configurações.'],
[/^Ambiguous (ads|crm) columns: (.+)\. Choose the correct columns in detection settings\.$/, 'Colunas ambíguas ($1): $2. Escolha as colunas corretas nas configurações.'],
];
Object.assign(portuguese, {'input rows':'linhas de entrada','accepted':'aceitas','duplicates':'duplicatas','quarantined':'isoladas'});
